on: [push]

name: 'Extract Windows 10 sdk'

permissions:
  contents: write

jobs:
  upload-release:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Download SDK installer
      run: curl -SL --output C:\sdksetup.exe https://go.microsoft.com/fwlink/p/?LinkId=323507

    - name: Install SDK
      run: C:\sdksetup.exe /features OptionId.WindowsDesktopSoftwareDevelopmentKit OptionId.NetFxSoftwareDevelopmentKit
    
    - name: Make folders for archive
      run: mkdir C:\include && mkdir C:\lib

    - name: Copy files to folderspowe
      run: (copy "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\" "C:\include\") && (copy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um" "C:\lib\")
    
    - name: Create archive for sdk
      run: Compress-Archive -Path "C:\:include", "C:\lib" -DestinationPath "C:\winsdk.zip"

    - name: create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 10
        release_name: Windows SDK 10
        draft: false
        prerelease: false   

    - name: upload windows 10 sdk
      id: upload-windows-10
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: C:\winsdk.zip
        asset_name: winsdk.zip
        asset_content_type: application/zip