on: [push]

name: 'Extract Windows 10 sdk'

permissions:
  contents: write

jobs:
  upload-release:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Download SDK installer
      run: curl -SL --output C:\sdksetup.exe https://go.microsoft.com/fwlink/p/?LinkId=323507

    - name: Install SDK
      run: C:\sdksetup.exe /features OptionId.WindowsDesktopSoftwareDevelopmentKit OptionId.NetFxSoftwareDevelopmentKit
    
    - name: Make folders for archive
      run: mkdir C:\sdk\include && mkdir C:\sdk\lib

    - name: Copy lib files
      run:  Copy-Item -Path "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\*" -Destination "C:\sdk\lib" -Recurse -Force -ErrorAction Continue

    - name: Copy include files
      run:  Copy-Item -Path "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\*" -Destination "C:\sdk\include" -Recurse -Force -ErrorAction Continue

    - name: Create archive for unmodified sdk
      run: Compress-Archive -Path "C:\sdk\include", "C:\sdk\lib" -DestinationPath "C:\winsdk_unmodified.zip"

    - name: Convert filenames to lowercase for linux compatability
      run: Get-ChildItem -r C:/sdk | Where {!$_.PSIsContainer} | Rename-Item -NewName {$_.FullName.ToLower()}

    - name: Flatten includes folder
      run: Get-ChildItem -Path "C:\sdk\include" -Recurse -File | Move-Item -Destination "C:\sdk\unclude" -Force

    - name: Flatten libs filer
      run: |
        $basePath = "C:\sdk\lib"

        Get-ChildItem -Path $basePath -Directory | ForEach-Object {
            Get-ChildItem -Path $_.FullName -Directory | ForEach-Object {
                $newPath = Join-Path -Path $basePath -ChildPath $_.Name
                Move-Item -Path $_.FullName -Destination $newPath -Force
            }
            Remove-Item -Path $_.FullName -Force -Recurse
        }
    
    - name: Create archive for modified sdk
      run: Compress-Archive -Path "C:\sdk\include", "C:\sdk\lib" -DestinationPath "C:\winsdk.zip"

    - name: create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 10
        release_name: Windows SDK 10
        draft: false
        prerelease: false   

    - name: upload unmodified windows 10 sdk
      id: upload-windows-10-unmodified
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: C:\winsdk_unmodified.zip
        asset_name: winsdk_unmodified.zip
        asset_content_type: application/zip
    
    - name: upload windows 10 sdk
      id: upload-windows-10
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: C:\winsdk.zip
        asset_name: winsdk.zip
        asset_content_type: application/zip